### ISSUE TITLE
Fix the inability to run inventory against dfds-master account.

### ISSUE THREAD

**Issue by wiredworm** [dfds/aws-inventory-orchestrator#16]
We have completed an initial execution of the inventory tool and it has become clear that the dfds-master account is not included in the inventory.

The reason for this is that the billing account does not have an OrgRole defined.  This means that the CE-CLI is unable to deploy the inventory role to this account, and as a result the audit cannot execute.

You could deploy the inventory role manually but this would result in a special case just for this account and if the trust or policy changes in the future then it could get messy.  Ideally we should probably define an OrgRole in the master account, although it doesn't necessarily need to have full permissions, just those needed for the deployment to work.

**Comment by avnes** [comment]
This needs to be refined, for instance:
- What permissions does an OrgRole in the master account need?
- Create a Terraform module for the OrgRole in the master account and apply in pre-pipeline?
