### ISSUE TITLE
Replace "upload" container with Go program

### ISSUE THREAD

**Issue by abstrask** [dfds/aws-inventory-orchestrator#5]
Once the inventory report has been generated, it's uploaded by a one-line Bash command using Amazon's AWS CLI Docker image.

The syntax is convoluted and exception handling is minimal, but it seems to get the job done:

```golang
uploadArg := fmt.Sprintf("set -u; FILE=/recon/output.json; [ -f \"$FILE\" ] && { echo Uploading \"$FILE\" to \"%s\"; aws s3 cp --no-progress \"$FILE\" %s; } || { echo Output file \"$FILE\" not found!; exit 404; }", s3Path, s3Path)
```

The image, command and arguments is defined in the [`orchestrator` Go program](https://github.com/dfds/aws-inventory-orchestrator/blob/32801d595fa8cdd5d12a8aa09189c49149bdc71f/orchestrator/main.go#L55).

At some points, we may want to replace this crude one-liner with a slightly more sophisticated program, with better exception handling.

It may also be desirable to add support for Gunzip'ing before uploading reports to S3, as a report from just a sandbox account was 2+ MB (and we have 200+ accounts).

This is probably not high priority.

**Comment by avnes** [comment]
@abstrask I think this issue needs more refining. As a start explain what the "upload" container is, where it is and any other important prerequisites.

**Comment by abstrask** [comment]
@avnes How about now?

**Comment by avnes** [comment]
Perfect :)
